# Generated by Django 4.2 on 2023-07-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default='Face Cream', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.product'),
        ),
    ]
